### ISSUE TITLE
Flutter Project TO Do List

### ISSUE THREAD

**Issue by abhashgoyal** [Git-For-Geeks/Flutter-Projects#5]

**Comment by JayDubey19** [comment]
@abhashgoyal  please complete previous problem statement of which you have created issue for i.e calculator then you can go with this.

**Comment by abhashgoyal** [comment]
Please assign this issue to me...i will add the previous issue asap

**Comment by abhashgoyal** [comment]
Sorry I got a little bit late while working on this project, I have managed to make a ui for the user..but could you please guide what all things are needed to be added in TO DO list apart from being adding a note widgets
